
[phases.setup]
#aptPkgs = ["...", "wget","xvfb","unzip","chromium","chromium-chromedriver"]

CMDS =  ["apt-get", "install", "-y","wget", "xvfb", "unzip"]

[start]
cmd = "uvicorn stratum-miner-web:app --host 0.0.0.0 --port $PORT"
