
[phases.setup]

aptPkgs = ["...", "wget","xvfb","unzip"]
cmds = ["wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -"]


[start]
cmd = "uvicorn stratum-miner-web:app --host 0.0.0.0 --port $PORT"
