
[phases.setup]

aptPkgs = ["...", "wget","xvfb","unzip"]
cmds = ["wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -"]
cmds = ['echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list']
cmds = ["apt-get update -y"]
cmds = ["apt-get install -y google-chrome-stable"]


[start]
cmd = "uvicorn stratum-miner-web:app --host 0.0.0.0 --port $PORT"
